version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - pgdata:/var/lib/postgresql/data/
  redis:
    image: redis
    # volumes:
    #   - redisdata:/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis